#! /usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# expects pr title in format acb-123-foo-bar-baz
TITLE=$(\
  echo $(git rev-parse --abbrev-ref HEAD) \
    | sed -E 's/[-|_]/ /g' \
    | sed -E 's/(\w+) ([0-9]+)/[\U\1-\2]/' \
    | sed -E 's/ (\w)/ \U\1/g' \
  )

echo "enter PR body"
read BODY

gh pr create --assignee "@me" --base dev --title "$TITLE" --body "$BODY"

gh pr view --jq .title --json title
gh pr view --jq .url --json url
