#! /bin/bash

NVIM="$HOME/nvim"
source "$NVIM/aliases.sh"
source "$NVIM/commands.sh"
source "$NVIM/deno.sh"
source "$NVIM/clip.sh"
source "$NVIM/nvim.sh"
source "$NVIM/oh-my-bash.sh"
source "$NVIM/rust.sh"

