#! /bin/bash

NVIM="$HOME/nvim"
source "$NVIM/aliases.sh"
source "$NVIM/commands.sh"
source "$NVIM/deno.sh"
source "$NVIM/clip.sh"
source "$NVIM/nvim.sh"
source "$NVIM/rust.sh"
eval "$(starship init bash)"

export PATH="$HOME/.local/bin:$PATH"

if [ -f "$HOME/.bashrc_local" ]
then
  source "$HOME/.bashrc_local"
fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
