#! /bin/bash

NVIM="$HOME/nvim"

export PATH="$HOME/.local/bin:$PATH"

if [ -f "$HOME/.bashrc_local" ]
then
  source "$HOME/.bashrc_local"
fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
. "$HOME/.cargo/env"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
