#! /usr/bin/fish

# might be for rust analyzer?
set -x PATH "$HOME/.local/bin:$PATH"
set -x PATH "$HOME/.cargo/bin:$PATH"

set NVIM "$HOME/nvim"
source "$NVIM/aliases.fish"
source "$NVIM/commands.fish"
source "$NVIM/deno.fish"
source "$NVIM/clip.fish"
source "$NVIM/nvim.fish"
starship init fish | source

if test -f "$NVIM/dotfishlocal"
  source "$NVIM/dotfishlocal"
end

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# set -gx AWS_PROFILE pfes

