#! /usr/bin/fish

set NVIM "$HOME/nvim"
source "$NVIM/aliases.fish"
source "$NVIM/commands.fish"
source "$NVIM/deno.fish"
source "$NVIM/clip.fish"
source "$NVIM/nvim.fish"
source "$NVIM/rust.fish"
starship init fish | source

# might be for rust analyzer?
set -x PATH "$HOME/.local/bin:$PATH"

# for nvm
nvm use lts/gallium

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
set -gx AWS_PROFILE pfes
