local script_path = debug.getinfo(1, "S").source:sub(2)
local script_dir = script_path:match("(.*)/") or "."

package.path = script_dir .. "/?.lua;" .. package.path

local render = require("render")
local highlight = require("highlight")

local DEFAULT_LIGHT = "minilight"
local DEFAULT_DARK = "miniwinter"

local M = {}

local function load_palette(name)
  local path = script_dir .. "/themes/" .. name .. ".lua"
  local fd = io.open(path, "rb")
  if not fd then
    error("palette not found: " .. path .. "\n  run: nvim --headless -c 'luafile scripts/site/themes/dump.lua' -c 'qa'")
  end
  fd:close()
  return dofile(path)
end

local function color_for(palette, capture)
  local n = capture
  while n and n ~= "" do
    if palette.captures[n] then return palette.captures[n] end
    n = n:match("^(.-)%.[^.]+$")
  end
  return nil
end

local function emit_highlights_css(light, dark, captures)
  local sorted = {}
  for cap in pairs(captures) do sorted[#sorted + 1] = cap end
  table.sort(sorted)

  local out = {
    "/* generated by build.lua -- do not edit by hand */",
    ":root {",
    ("  --code-bg: light-dark(%s, %s);"):format(light.bg, dark.bg),
    ("  --code-fg: light-dark(%s, %s);"):format(light.fg, dark.fg),
    "}",
  }
  for _, cap in ipairs(sorted) do
    local lc = color_for(light, cap)
    local dc = color_for(dark, cap)
    if lc or dc then
      local class = highlight.class_for(cap)
      out[#out + 1] = ("." .. class .. " { color: light-dark(%s, %s); }"):format(lc or light.fg, dc or dark.fg)
    end
  end
  out[#out + 1] = ""
  return table.concat(out, "\n")
end

local function read_file(path)
  local fd = io.open(path, "rb")
  if not fd then return nil end
  local s = fd:read("*a")
  fd:close()
  return s
end

local function write_file(path, content)
  local dir = path:match("(.*)/")
  if dir then vim.fn.mkdir(dir, "p") end
  local fd, err = io.open(path, "wb")
  if not fd then error("cannot write " .. path .. ": " .. tostring(err)) end
  fd:write(content)
  fd:close()
end

local function list_markdown(dir)
  local out = {}
  for name, kind in vim.fs.dir(dir, { depth = 16 }) do
    if kind == "file" and name:match("%.md$") then
      out[#out + 1] = name
    end
  end
  return out
end

local function substitute(template, vars)
  local result = template
  for key, value in pairs(vars) do
    result = result:gsub("{{" .. key .. "}}", function() return value end)
  end
  return result
end

function M.build_all()
  local content_dir = script_dir .. "/content"
  local dist_dir = script_dir .. "/dist"
  vim.fn.mkdir(dist_dir, "p")

  local template = read_file(script_dir .. "/template.html")
  if not template then error("template.html not found at " .. script_dir) end

  local css = read_file(script_dir .. "/style.css")
  if css then write_file(dist_dir .. "/style.css", css) end

  local light_name = os.getenv("SITE_THEME_LIGHT") or DEFAULT_LIGHT
  local dark_name = os.getenv("SITE_THEME_DARK") or DEFAULT_DARK
  local light = load_palette(light_name)
  local dark = load_palette(dark_name)

  render.captures_seen = {}

  local files = list_markdown(content_dir)
  for _, rel in ipairs(files) do
    local src = read_file(content_dir .. "/" .. rel)
    local body, title = render.render(src)
    local html = substitute(template, {
      title = title,
      body = body,
      light_name = light_name,
      dark_name = dark_name,
    })
    local out_rel = rel:gsub("%.md$", ".html")
    write_file(dist_dir .. "/" .. out_rel, html)
    io.write("built " .. out_rel .. "\n")
  end
  local hlcss = emit_highlights_css(light, dark, render.captures_seen)
  write_file(dist_dir .. "/highlights.css", hlcss)
  io.write(("built highlights.css (light=%s dark=%s)\n"):format(light_name, dark_name))
end

if ... == nil then M.build_all() end

return M
