export def main [] {
  [
    [name                                  srcWindows                                srcUnix                                             srcMac ];
    [stylua                                null                                      brew                                                brew]
    [harlequin                             null                                      brew                                                brew]
    [powershell                            null                                      brew                                                brew]
    [poppler                               null                                      brew                                                brew]
    [deno                                  scoop                                     brew                                                brew]
    [fd                                    scoop                                     brew                                                brew]
    [fnm                                   scoop                                     brew                                                brew]
    [fzf                                   scoop                                     brew                                                brew]
    [gcc                                   scoop                                     brew                                                brew]
    [gh                                    scoop                                     brew                                                brew]
    [lua-language-server                   scoop                                     brew                                                brew]
    [go                                    null                                      brew                                                brew]
    [gopls                                 null                                      brew                                                brew]
    [marksman                              scoop                                     brew                                                brew]
    [neovim                                scoop                                     brew                                                brew]
    [nushell                               scoop=nu                                  brew                                                brew]
    [ripgrep                               scoop                                     brew                                                brew]
    [bat                                   scoop                                     brew                                                brew]
    [vcredist2022                          scoop                                     null                                                null]
    ['nerd-fonts/0xProto-NF-Mono'          scoop                                     null                                                brew=font-0xproto-nerd-font]
    [gsudo                                 scoop                                     null                                                null]
    [make                                  scoop                                     null                                                null]
    [komorebi                              scoop                                     null                                                'brew=lgug2z/tap;komorebi-for-mac']
    [whkd                                  scoop                                     null                                                'brew=asmvik/formulae/skhd']
    [gpg4win                               scoop                                     null                                                null]
    [discord                               winget=discord.discord                    null                                                null]
    [chrome                                winget=google.chrome                      null                                                null]
    [visualstudiocode                      winget=microsoft.visualstudiocode         null                                                null]
    [dockerdesktop                         winget=docker.dockerdesktop               null                                                null]
    [orbstack                              null                                      null                                                brew]
    [postgres                              null                                      null                                                'brew=postgresql@18']
    [dbeaver                               winget=dbeaver.dbeaver                    null                                                null]
    [gpg4win                               winget=GnuPG.Gpg4win                      null                                                null]
    [devtoys                               winget=DevToys-app.DevToys                null                                                null]
    [zoxide                                scoop                                     brew                                                brew]
    [jj                                    scoop                                     brew                                                brew]
    [jjui                                  null                                      brew                                                brew]
    [dockerfile-language-server-nodejs     null                                      npm                                                 npm]
    [graphql-language-service-cli          null                                      npm                                                 npm]
    [typescript                            npm                                       npm                                                 npm]
    [@vue/language-server                  null                                      null                                                null]
    [@prisma/language-server               null                                      null                                                null]
    [typescript-language-server            null                                      null                                                null]
    [@vtsls/language-server                null                                      npm                                                 npm]
    [prettier                              null                                      npm                                                 npm]
    [tree-sitter-cli                       npm                                       npm                                                 npm]
    [vscode-langservers-extracted          null                                      npm                                                 npm]
    [@tailwindcss/language-server          null                                      null                                                null]
    [claude-code                           winget=Anthropic.ClaudeCode               'brew=claude-code@latest'                           'brew=claude-code@latest']
    [pandoc                                null                                      brew                                                brew]
    [yq                                    scoop                                     brew                                                brew]
    [git-credential-manager                null                                      dotnet                                              dotnet]
    [dotnet-ef                             null                                      dotnet                                              dotnet]
    [csharpier                             null                                      dotnet                                              dotnet]
    # TODO: wait until out of prerelease https://www.nuget.org/packages/roslyn-language-server/
    # [roslyn-language-server                null                                      dotnet                                              dotnet]
    [func                                  winget=Microsoft.Azure.FunctionsCoreTools 'brew=azure/functions;azure-functions-core-tools@4' 'brew=azure/functions;azure-functions-core-tools@4']
    [azure-storage-explorer                winget=Microsoft.Azure.StorageExplorer    null                                                null]
    [win32yank                             winget=equalsraf.win32yank                null                                                null]
    [Logitech.OptionsPlus                  winget                                    null                                                brew=logi-options+]
  ]
}
