#! /usr/bin/fish

# might be for rust analyzer?
set -x PATH "$HOME/.local/bin:$PATH"
set -x PATH "$HOME/.cargo/bin:$PATH"
set -x PATH "$HOME/.local/bin/flutter/bin:$PATH"
set -x PATH "$HOME/.local/bin/jdk-19.0.2/bin:$PATH"

set FISH "$HOME/nvim/fish"
source "$FISH/aliases.fish"
source "$FISH/deno.fish"
source "$FISH/clip.fish"
source "$FISH/show.fish"
source "$FISH/nvim.fish"
starship init fish | source

if test -f "$FISH/dotfishlocal"
  source "$FISH/dotfishlocal"
end

nvm use lts > /dev/null

# https://learn.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#fish
complete -f -c dotnet -a "(dotnet complete (commandline -cp))"
export PATH="$HOME/.dotnet/tools:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# set -gx AWS_PROFILE pfes

