#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
editor = "nvim"
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
default-command = "log"

[user]
name = "Paul Fesenmeier"
email = "pfesenmeier@gmail.com"

[revsets]
bookmark-advance-to = "@-"

# [aliases]
# nt = ["new", "trunk()"]
