# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

right_format = "$time"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '-5'
time_range = '10:00:00-14:00:00'

