-- Dump mini.nvim color schemes into static palette files for build.lua.
-- Run from a real nvim session (so init.lua + mini.nvim are loaded):
--
--   nvim --headless -c 'luafile scripts/site/themes/dump.lua' -c 'qa'
--
-- Each scheme is applied in turn, capture foregrounds are harvested into a
-- plain-Lua table, and the result is written to themes/<scheme>.lua. The
-- generated files are committed; the build itself never applies a colorscheme.

local CAPTURES = {
  "comment",
  "string", "string.escape", "string.special", "string.special.url",
  "number", "boolean",
  "constant", "constant.builtin", "constant.macro",
  "function", "function.builtin", "function.method", "function.call",
  "function.method.call", "function.macro",
  "constructor",
  "keyword", "keyword.return", "keyword.import", "keyword.function",
  "keyword.operator", "keyword.conditional", "keyword.repeat",
  "keyword.exception", "keyword.modifier", "keyword.coroutine",
  "keyword.directive",
  "operator",
  "type", "type.builtin", "type.definition",
  "variable", "variable.builtin", "variable.member", "variable.parameter",
  "property", "label", "attribute", "namespace", "module",
  "punctuation.bracket", "punctuation.delimiter", "punctuation.special",
  "tag", "tag.attribute", "tag.delimiter",
}

local SCHEMES = { "miniwinter", "minisummer", "minispring", "miniautumn" }

-- Mini's named schemes are all dark. For light variants, drive mini.hues
-- directly with chosen base colors -- it derives a full palette from them.
-- Edit the background/foreground here, re-run dump, commit the result.
local CUSTOM_HUES = {
  minilight = { background = "#f6f3eb", foreground = "#1a1f24" },
}

local function hex(n)
  if not n then return nil end
  return string.format("#%06x", n)
end

local function fg_for(name)
  while name and name ~= "" do
    local hl = vim.api.nvim_get_hl(0, { name = "@" .. name, link = false })
    if hl and hl.fg then return hex(hl.fg) end
    local stripped = name:match("^(.-)%.[^.]+$")
    if not stripped then break end
    name = stripped
  end
  return nil
end

local function apply(name)
  if CUSTOM_HUES[name] then
    require("mini.hues").setup(CUSTOM_HUES[name])
  else
    vim.cmd("colorscheme " .. name)
  end
end

local function dump_palette(scheme)
  apply(scheme)
  local normal = vim.api.nvim_get_hl(0, { name = "Normal", link = false }) or {}
  local out = { "-- generated by themes/dump.lua -- do not edit by hand", "return {" }
  table.insert(out, string.format("  bg = %q,", hex(normal.bg) or "#000000"))
  table.insert(out, string.format("  fg = %q,", hex(normal.fg) or "#ffffff"))
  table.insert(out, "  captures = {")
  for _, cap in ipairs(CAPTURES) do
    local color = fg_for(cap)
    if color then
      table.insert(out, string.format("    [%q] = %q,", cap, color))
    end
  end
  table.insert(out, "  },")
  table.insert(out, "}")
  table.insert(out, "")
  return table.concat(out, "\n")
end

local script_path = debug.getinfo(1, "S").source:sub(2)
local script_dir = script_path:match("(.*)/") or "."

local all = {}
for _, s in ipairs(SCHEMES) do all[#all + 1] = s end
for name in pairs(CUSTOM_HUES) do all[#all + 1] = name end

for _, scheme in ipairs(all) do
  local ok, content_or_err = pcall(dump_palette, scheme)
  if not ok then
    io.stderr:write("dump failed for " .. scheme .. ": " .. tostring(content_or_err) .. "\n")
  else
    local path = script_dir .. "/" .. scheme .. ".lua"
    local fd = assert(io.open(path, "wb"))
    fd:write(content_or_err)
    fd:close()
    io.write("dumped " .. scheme .. " -> " .. path .. "\n")
  end
end
